### ISSUE TITLE
Research crypto data API

### ISSUE THREAD

**Issue by lildonpancho** [PDXPythonPirates/ppp-project-2#25]
As a developer, I need a data source to populate various areas of the application. Research should be documented somewhere (README, Google Sheet, etc.) and shared with everyone.

Research topics
---
* Is it free? What does the free tier offer?
* What is the process for acquiring an API key?
* What is the request limit?

**Comment by CloudF1sh** [comment]
**CoinGecko**
[](https://www.coingecko.com/)
Documentation: 
[](https://www.coingecko.com/en/api/documentation)
Free API Plan	
50 calls/minute (varies)


Shared infrastructure

30+ market data endpoints
50+ fiat/crypto conversions
8+ years historical data
12,000+ crypto assets coverage

FAQ Support


**KuCoin**
[](https://www.kucoin.com/)
Documentation:
[](https://docs.kucoin.com/#general)
Pricing:
Essential Free

This API might be one of our best options .  It definitely looks to have a lot of useful features that are relevant to what we want in this project. Only common complaint is bad server latency.




**Nomics**
[](https://nomics.com/)
Documentation:
[](https://nomics.com/docs)
Pricing:
[](https://p.nomics.com/pricing)


Seemingly versatile, and unlimited requests at the free tier (or so it claims).  What is not to love?



**Messari**
[](https://messari.io/)
Documentation:
[](https://messari.io/api/docs)
Pricing:
Basic API is Free and provides crypto prices, market data metrics, on-chain metrics, and qualitative information.

Good option for creating custom solutions.  Seems to be geared towards traders and seems to be well recognized within the Crypto community.
